"""Add status column to risks

Revision ID: 1965899b27ea
Revises: 79af8e997644
Create Date: 2025-08-07 13:26:51.051738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1965899b27ea'
down_revision = '79af8e997644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('OPEN', 'IN_PROGRESS', 'MITIGATED', 'ACCEPTED', name='riskstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'Open'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('OPEN', 'IN_PROGRESS', 'MITIGATED', 'ACCEPTED', name='riskstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'Open'"))

    # ### end Alembic commands ###
