"""Allow NULL mapping_id in reviews

Revision ID: a05230391b56
Revises: 7d3b387d7cb4
Create Date: 2025-08-06 11:35:20.445306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a05230391b56'
down_revision = '7d3b387d7cb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('mapping_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('mapping_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
