"""Add details to risks

Revision ID: b11c89f37038
Revises: c3af2e9e8452
Create Date: 2025-08-06 16:25:43.126829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b11c89f37038'
down_revision = 'c3af2e9e8452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.drop_column('details')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
