"""Add details to risks

Revision ID: ef1cd37a0a2e
Revises: b11c89f37038
Create Date: 2025-08-06 16:28:26.658933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef1cd37a0a2e'
down_revision = 'b11c89f37038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.drop_column('details')

    # ### end Alembic commands ###
